### Подключаем пакет

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

## Concat

In [2]:
arr = np.arange(12).reshape((3, 4))
arr1 = np.arange(15).reshape((3, 5))
print(arr)
np.concatenate([arr, arr1], axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 10, 11, 12, 13, 14]])

In [3]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])

In [4]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [5]:
pd.concat([s1, s3, s2], axis=1)

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
f  NaN  5.0  NaN
g  NaN  6.0  NaN
c  NaN  NaN  2.0
d  NaN  NaN  3.0
e  NaN  NaN  4.0

In [6]:
s4 = pd.concat([s1, s3])
display(s4)
display( pd.concat([s1, s4], axis=1,sort=True) )
pd.concat([s1, s4], axis=1, join='inner', sort=True)

a    0
b    1
f    5
g    6
dtype: int64

     0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

   0  1
a  0  0
b  1  1

In [7]:
pd.concat([s1, s4], axis=1, join_axes=[['a', 'c', 'b', 'e']]) # нет команды по порядку объединения

TypeError: concat() got an unexpected keyword argument 'join_axes'

In [8]:
pd.concat([s1, s4], axis=1, sort=True)

     0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [9]:
pd.concat([s1, s4], axis=1, sort=True)

     0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [10]:
pd.concat([s1, s4], axis=1, sort=True).reindex(['a', 'c', 'b', 'e'])

     0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  1.0
e  NaN  NaN

In [11]:
display(s1, s1, s3)

a    0
b    1
dtype: int64

a    0
b    1
dtype: int64

f    5
g    6
dtype: int64

In [12]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])
display(result)
result.unstack()

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

         a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [13]:
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'],sort=False)

   one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [14]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                   columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                   columns=['three', 'four'])
display(df1)
display(df2)
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'],sort=False)

   one  two
a    0    1
b    2    3
c    4    5

   three  four
a      5     6
c      7     8

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [15]:
pd.concat({'level1': df1, 'level2': df2}, axis=1,sort=False)

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [16]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'],
          names=['upper', 'lower'],sort=False)

upper level1     level2
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [17]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
display(df1)
display(df2)

          a         b         c         d
0  0.026761 -0.033103  2.337256 -0.383956
1 -0.581557 -0.230605 -0.046287 -0.910036
2  1.453383  0.056673 -1.404011  0.862665

          b         d         a
0  1.058476  0.498168  0.407998
1  0.046358  0.511260 -0.708062

In [18]:
pd.concat([df1, df2], ignore_index=True,sort=False)

          a         b         c         d
0  0.026761 -0.033103  2.337256 -0.383956
1 -0.581557 -0.230605 -0.046287 -0.910036
2  1.453383  0.056673 -1.404011  0.862665
3  0.407998  1.058476       NaN  0.498168
4 -0.708062  0.046358       NaN  0.511260