### Подключаем пакет

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

## GroupBy и Agg

In [2]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one -1.514831  0.627470
1    a  two  0.488808 -0.489511
2    b  one  0.306418  0.067443
3    b  two  1.914731 -0.242705
4    a  one  0.531183  1.239097

In [3]:
grouped = df['data1'].groupby(df['key1']).sum()
grouped

key1
a   -0.494840
b    2.221149
Name: data1, dtype: float64

In [4]:
means = df['data1'].groupby([df['key1'], df['key2']]).mean()
means

key1  key2
a     one    -0.491824
      two     0.488808
b     one     0.306418
      two     1.914731
Name: data1, dtype: float64

In [5]:
means.unstack()

key2       one       two
key1
a    -0.491824  0.488808
b     0.306418  1.914731

In [6]:
states = np.array(['Ohio', 'California', 'California', 'Ohio', 'Ohio'])
years = np.array([2005, 2005, 2006, 2005, 2006])
df['data1'].groupby([states, years]).mean()

California  2005    0.488808
            2006    0.306418
Ohio        2005    0.199950
            2006    0.531183
Name: data1, dtype: float64

In [7]:
df

  key1 key2     data1     data2
0    a  one -1.514831  0.627470
1    a  two  0.488808 -0.489511
2    b  one  0.306418  0.067443
3    b  two  1.914731 -0.242705
4    a  one  0.531183  1.239097

In [10]:
df.groupby('key1').mean() # щибка вызвание наличием не числового стобца "key2"

TypeError: agg function failed [how->mean,dtype->object]

In [12]:
# обход подобной ошибки, для понимающих, что делается

df.groupby('key1').mean(numeric_only=True)

         data1     data2
key1
a    -0.164947  0.459019
b     1.110575 -0.087631

In [13]:
df.groupby(['key1', 'key2']).mean()

              data1     data2
key1 key2
a    one  -0.491824  0.933284
     two   0.488808 -0.489511
b    one   0.306418  0.067443
     two   1.914731 -0.242705

In [14]:
df.groupby(['key1', 'key2']).size()

key1  key2
a     one     2
      two     1
b     one     1
      two     1
dtype: int64

In [15]:
df.groupby('key1')

In [16]:
for name, group in df.groupby('key1'):
    display(name)
    display(group)

'a'

  key1 key2     data1     data2
0    a  one -1.514831  0.627470
1    a  two  0.488808 -0.489511
4    a  one  0.531183  1.239097

'b'

  key1 key2     data1     data2
2    b  one  0.306418  0.067443
3    b  two  1.914731 -0.242705

In [17]:
for (k1, k2), group in df.groupby(['key1', 'key2']):
    display((k1, k2))
    display(group)

('a', 'one')

  key1 key2     data1     data2
0    a  one -1.514831  0.627470
4    a  one  0.531183  1.239097

('a', 'two')

  key1 key2     data1     data2
1    a  two  0.488808 -0.489511

('b', 'one')

  key1 key2     data1     data2
2    b  one  0.306418  0.067443

('b', 'two')

  key1 key2     data1     data2
3    b  two  1.914731 -0.242705

In [18]:
pieces = dict(list(df.groupby('key1')))
pieces['b']

  key1 key2     data1     data2
2    b  one  0.306418  0.067443
3    b  two  1.914731 -0.242705

### Разрезать данные по типам столбцов (группировки они по строкам, а тут столбцы)

In [67]:
# из groupby удалили поддержку axis
display(df.dtypes)
display(df.T)
grouped = df.T.groupby(df.dtypes)

key1      object
key2      object
data1    float64
data2    float64
dtype: object

              0         1         2         3         4
key1          a         a         b         b         a
key2        one       two       one       two       one
data1 -1.514831  0.488808  0.306418  1.914731  0.531183
data2   0.62747 -0.489511  0.067443 -0.242705  1.239097

In [68]:
for dtype, group in grouped:
    print(dtype)
    print(group.T)

float64
      data1     data2
0 -1.514831   0.62747
1  0.488808 -0.489511
2  0.306418  0.067443
3  1.914731 -0.242705
4  0.531183  1.239097
object
  key1 key2
0    a  one
1    a  two
2    b  one
3    b  two
4    a  one

In [69]:
display(df)
df.groupby(['key1', 'key2'])[['data2']].mean()

  key1 key2     data1     data2
0    a  one -1.514831  0.627470
1    a  two  0.488808 -0.489511
2    b  one  0.306418  0.067443
3    b  two  1.914731 -0.242705
4    a  one  0.531183  1.239097

              data2
key1 key2
a    one   0.933284
     two  -0.489511
b    one   0.067443
     two  -0.242705

In [70]:
people = pd.DataFrame(np.random.randn(5, 5),
                      columns=['a', 'b', 'c', 'd', 'e'],
                      index=['Joe', 'Steve', 'Wes', 'Jim', 'Travis'])
people.iloc[2:3, [1, 2]] = np.nan # Add a few NA values
people

               a         b         c         d         e
Joe    -1.018726  0.273252 -0.993737  0.861550 -0.487536
Steve   2.826559  1.765044  0.737884 -0.907281 -1.000015
Wes    -0.195607       NaN       NaN  1.425330  0.575853
Jim    -2.245359  0.141497 -1.510507 -0.465171 -1.355524
Travis -1.354270 -0.007346  1.838233 -2.145404 -1.902948

In [71]:
mapping = {'a': 'red', 'b': 'red', 'c': 'blue',
           'd': 'blue', 'e': 'red', 'f' : 'orange'}

In [72]:
# Опять колонки столбцы
by_column = people.T.groupby(mapping)
by_column.sum().T

            blue       red
Joe    -0.132187 -1.233010
Steve  -0.169397  3.591589
Wes     1.425330  0.380245
Jim    -1.975678 -3.459386
Travis -0.307170 -3.264564

In [73]:
map_series = pd.Series(mapping)
display(map_series)
people.T.groupby(map_series).count().T

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: object

        blue  red
Joe        2    3
Steve      2    3
Wes        1    2
Jim        2    3
Travis     2    3

In [74]:
display(people)
people.groupby(len).sum()

               a         b         c         d         e
Joe    -1.018726  0.273252 -0.993737  0.861550 -0.487536
Steve   2.826559  1.765044  0.737884 -0.907281 -1.000015
Wes    -0.195607       NaN       NaN  1.425330  0.575853
Jim    -2.245359  0.141497 -1.510507 -0.465171 -1.355524
Travis -1.354270 -0.007346  1.838233 -2.145404 -1.902948

          a         b         c         d         e
3 -3.459693  0.414749 -2.504244  1.821709 -1.267207
5  2.826559  1.765044  0.737884 -0.907281 -1.000015
6 -1.354270 -0.007346  1.838233 -2.145404 -1.902948

In [75]:
key_list = ['one', 'one', 'one', 'two', 'two']
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one -1.018726  0.273252 -0.993737  0.861550 -0.487536
  two -2.245359  0.141497 -1.510507 -0.465171 -1.355524
5 one  2.826559  1.765044  0.737884 -0.907281 -1.000015
6 two -1.354270 -0.007346  1.838233 -2.145404 -1.902948

In [76]:
columns = pd.MultiIndex.from_arrays([['US', 'US', 'US', 'JP', 'JP'],
                                    [1, 3, 5, 1, 3]],
                                    names=['cty', 'tenor'])
hier_df = pd.DataFrame(np.random.randn(4, 5), columns=columns)
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0      0.063293 -0.449277  1.435846 -0.209052 -0.396115
1     -1.254513  0.733062  1.416680 -0.141156  0.705118
2     -0.664690  0.406243 -0.391571  1.010535 -1.354265
3     -0.233727 -0.227960 -0.964134  0.502912  0.002675

In [82]:
hier_df.T.groupby(level='cty').count().T

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

In [83]:
display(df)
grouped = df.groupby('key1')
grouped['data1'].quantile(0.9)

  key1 key2     data1     data2
0    a  one -1.514831  0.627470
1    a  two  0.488808 -0.489511
2    b  one  0.306418  0.067443
3    b  two  1.914731 -0.242705
4    a  one  0.531183  1.239097

key1
a    0.522708
b    1.753900
Name: data1, dtype: float64

In [93]:
#### ВНИМАНИЕ в чем проблема? НАПИШИ работающий код!!!

def peak_to_peak(arr):
    return arr.max() - arr.min()

grouped.agg(peak_to_peak)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [95]:
grouped.describe()

     data1                                                              \
     count      mean       std       min       25%       50%       75%
key1
a      3.0 -0.164947  1.169226 -1.514831 -0.513012  0.488808  0.509995
b      2.0  1.110575  1.137249  0.306418  0.708496  1.110575  1.512653

               data2                                                    \
           max count      mean       std       min       25%       50%
key1
a     0.531183   3.0  0.459019  0.876529 -0.489511  0.068980  0.627470
b     1.914731   2.0 -0.087631  0.219308 -0.242705 -0.165168 -0.087631


           75%       max
key1
a     0.933284  1.239097
b    -0.010094  0.067443

In [102]:
grouped.describe(include='all').T

key1                 a         b
key2  count          3         2
      unique         2         2
      top          one       one
      freq           2         1
      mean         NaN       NaN
      std          NaN       NaN
      min          NaN       NaN
      25%          NaN       NaN
      50%          NaN       NaN
      75%          NaN       NaN
      max          NaN       NaN
data1 count        3.0       2.0
      unique       NaN       NaN
      top          NaN       NaN
      freq         NaN       NaN
      mean   -0.164947  1.110575
      std     1.169226  1.137249
      min    -1.514831  0.306418
      25%    -0.513012  0.708496
      50%     0.488808  1.110575
      75%     0.509995  1.512653
      max     0.531183  1.914731
data2 count        3.0       2.0
      unique       NaN       NaN
      top          NaN       NaN
      freq         NaN       NaN
      mean    0.459019 -0.087631
      std     0.876529  0.219308
      min    -0.489511 -0.242705
      25%      0.06898 -0.165168
      50%      0.62747 -0.087631
      75%     0.933284 -0.010094
      max     1.239097  0.067443